x = [1, 2, 3]
print(x)
x.insert(1, 4)
print("------------------")
print(x)
print("------------------")
x.append(2)
print(x)
print("------------------")
x.index(2)
print(x)
print("------------------")
x.pop(3)
x.remove(2)
print(x)
y = [2, 5, 6]
x.append(y)
print(x)
y.pop(2)
print("------------------")
print(x)
print(2)